# Generated by Django 3.2.8 on 2021-10-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active_user', models.PositiveSmallIntegerField(default=0, help_text='0=not active 1=active 2=ban 3=deleted')),
                ('api_token', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
